Homework1
belovmd/it-academy-python-winter pull request #10
Opened 2019-12-05 23:47 UTC by maryiaLichko

Maryia Lichko

2019-12-05 23:58 UTC, maryiaLichko commented
Homework 1,
 name: Maryia Lichko

2019-12-13 15:05 UTC, belovmd requested changes
No changes please fix

2019-12-19 16:34 UTC, belovmd reviewed
1. please remove second homework files
2. currently after issue-1 fix it's smth like +0,5 points. to improve it up to +2 please add additional tasks

2019-12-19 16:34 UTC, belovmd commented on homework1/my homework #1
> +
why do we need empty file?

2019-12-19 18:00 UTC, maryiaLichko commented
> * please remove second homework files
> * currently after issue-1 fix it's smth like +0,5 points. to improve it up to +2 please add additional tasks

Tasks are added
why should I remove 2nd homework?

2019-12-20 06:14 UTC, belovmd commented
> > * please remove second homework files
> > * currently after issue-1 fix it's smth like +0,5 points. to improve it up to +2 please add additional tasks
> 
> Tasks are added (2nd is in src folder*)
> why should I remove 2nd homework?

Because it's 1st homework
1st in Homework1
2nd in Homework2
etc. 
No need keep all code in one PR - it's inaccurate and difficult to review

2019-12-22 15:31 UTC, maryiaLichko commented
> > > * please remove second homework files
> > > * currently after issue-1 fix it's smth like +0,5 points. to improve it up to +2 please add additional tasks
> > 
> > 
> > Tasks are added (2nd is in src folder*)
> > why should I remove 2nd homework?
> 
> Because it's 1st homework
> 1st in Homework1
> 2nd in Homework2
> etc.
> No need keep all code in one PR - it's inaccurate and difficult to review

checks  done , please review

2020-01-03 10:38 UTC, belovmd reviewed
+1,5
please next time put tasks descriptions to files (it hasn't affected this HW)

2020-01-03 10:38 UTC, closed without merging