Homework4: Shevchuk Aleksei
belovmd/it-academy-python-winter pull request #100
Opened 2020-01-16 23:06 UTC by alex-shef

2020-02-23 15:51 UTC, belovmd requested changes
Please take a look at the next issues:

2020-02-23 15:51 UTC, belovmd commented on Homework4/task2.py
> +# 2. Города
what about Brest in Belarus and France?

2020-02-23 15:51 UTC, belovmd commented on Homework4/task2.py
> +for i in range(int(input("Enter the number of lists: "))):
where do we use i? 
for _ in ..

2020-02-23 15:51 UTC, belovmd commented on Homework4/task2.py
> +for i in range(int(input("Enter the number of cities: "))):
same issue

2020-02-23 15:51 UTC, belovmd commented on Homework4/task3.py
> +print("Number of different numbers:", len(set(lst1) | set(lst2)))
it doesn't solve task - we need other operator

2020-02-23 15:51 UTC, belovmd commented on Homework4/task5.py
> +pupils = [{input() for j in range(int(input()))} for i in range(int(input()))]
please add invitation string

2020-02-24 16:26 UTC, alex-shef commented on Homework4/task2.py
> +# 2. Города
fixed

2020-03-16 22:35 UTC, belovmd reviewed
8,5

2020-03-16 22:35 UTC, belovmd commented on Homework4/task2.py
> +    for country, cities in dct.items():
O(n*m) solution (n - num of requested cities m - size of dict)
in fact we miss dict advantages here

2020-03-16 22:35 UTC, closed without merging