Homework 1: Fedor Polikarpov
belovmd/it-academy-python-winter pull request #28
Opened 2019-12-08 11:05 UTC by FedorPolikarpov

2019-12-09 18:06 UTC, FedorPolikarpov commented
Случайно сюда скинул дз №2, решил просто переименовать, что бы новую не создавать и заново не скидывать)

2019-12-13 17:35 UTC, belovmd reviewed
please create PR's for each homework according our guidelines. 
please use homeworks branches according to our git guidelines

2020-03-16 22:04 UTC, belovmd requested changes
there is only one task in PR

2020-03-22 19:48 UTC, belovmd reviewed
only hello world
0 :(

2020-03-22 19:48 UTC, closed without merging