Homework4: Yauheni Chachukha
belovmd/it-academy-python-winter pull request #92
Opened 2020-01-12 13:30 UTC by chechuhae

2020-02-23 14:31 UTC, belovmd requested changes
Thank you for your work please take a look at next issues:

2020-02-23 14:31 UTC, belovmd commented on src/Cities.py
> +            # Check common cities. Example Brest in France and Belarus
great note

2020-02-23 14:31 UTC, belovmd commented on src/Words.py
> +str_1 = " asd£ 2 2    \n\n\n asd£  erer n\n\n !!232323\n\n    djkfj %%$£R(()) "
\+ \t \r

2020-02-23 14:31 UTC, belovmd commented on src/languages.py
> +lst_1 = []
unclear naming here and below

2020-03-15 15:20 UTC, chechuhae commented on src/languages.py
> +lst_1 = []
Did all tasks

2020-03-16 22:23 UTC, belovmd reviewed
8,5

2020-03-16 22:23 UTC, belovmd commented on src/languages.py
> +            print(symbol)
it's much more easier with set intersection and union

2020-03-16 22:24 UTC, closed without merging