Homework4: Alexander Zhuk
belovmd/it-academy-python-winter pull request #95
Opened 2020-01-12 16:39 UTC by ZhukAlexander90

2020-02-23 15:25 UTC, belovmd requested changes
Please address next issues:

2020-02-23 15:25 UTC, belovmd commented on Homework4_ZhukAlexander/task2_cities.py
> +"""
what about Brest in Belarus and France?

2020-02-23 15:25 UTC, belovmd commented on Homework4_ZhukAlexander/task3_num_list1.py
> +# print(set(first_list))
do we need these comments?

2020-02-23 15:25 UTC, belovmd commented on Homework4_ZhukAlexander/task4_num_list2.py
> +# print(set(first_list))
do we need these comments?

2020-02-23 15:25 UTC, belovmd commented on Homework4_ZhukAlexander/task5_languages.py
> +# print(student_list)
do we need it?

2020-02-23 15:25 UTC, belovmd commented on Homework4_ZhukAlexander/task6_ words.py
> +func = str.maketrans(dict.fromkeys(string.punctuation))
we don't need puctuation according to task description ) but overall it's cool

2020-02-23 15:25 UTC, belovmd commented on Homework4_ZhukAlexander/task7_evklid.py
> +print(first_num + second_num)
it's a cheat. we don't need sum according to algorithm.

2020-03-04 16:44 UTC, ZhukAlexander90 commented on Homework4_ZhukAlexander/task4_num_list2.py
> +# print(set(first_list))
No, I left it to myself

2020-03-04 16:44 UTC, ZhukAlexander90 commented on Homework4_ZhukAlexander/task3_num_list1.py
> +# print(set(first_list))
I left it to myself. for check

2020-03-04 16:45 UTC, ZhukAlexander90 commented on Homework4_ZhukAlexander/task5_languages.py
> +# print(student_list)
not necessary
need to delete?

2020-03-16 22:28 UTC, belovmd reviewed
7
overall it's inaccurate with redundant comments + task with cities has issues

2020-03-16 22:28 UTC, closed without merging